apiVersion: v1
kind: Service
metadata:
  name: coredb-service
  namespace: blog
  labels:
    app: coredb-service
spec:
  selector:
    app: coredb-service
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    protocol: TCP
  type: ClusterIP